---
- name: Copying /etc/motd file (TBS compliance)
  copy:
    src: motd
    dest: /etc/
    owner: root
    group: root
    mode: 0600

- name: Copying /etc/issue file (TBS compliance)
  copy:
    src: issue
    dest: /etc/
    owner: root
    group: root
    mode: 0600

- name: Copying /etc/issue.net file (TBS compliance)
  copy:
    src: issue.net
    dest: /etc/
    owner: root
    group: root
    mode: 0600
