---
- name: Removing execute permission bit from files that display messages at user login (TBS compliance)
  file:
    path: /etc/update-motd.d
    mode: 0644
    recurse: yes
  when: ansible_distribution == "Ubuntu"

- name: Adding execute permission bit to the directory that stores user login message files (TBS compliance)
  file:
    path: /etc/update-motd.d
    mode: 0755
    recurse: no
  when: ansible_distribution == "Ubuntu"

- name: Removing excessive permission bits from boot configuration file (TBS compliance)
  file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: 0600
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Removing excessive permission bits from log files (TBS compliance)
  file:
    path: /var/log
    mode: 0640
    recurse: yes

- name: Setting ownership and permission bits on TCP Wrappers deny file (TBS compliance)
  file:
    path: /etc/hosts.deny
    mode: 0644
    owner: root
    group: root

- name: Setting ownership and permission bits on TCP Wrappers allow file (TBS compliance)
  file:
    path: /etc/hosts.allow
    mode: 0644
    owner: root
    group: root

- name: Setting ownership and permission bits on syslog configuration file (TBS compliance)
  file:
    path: /etc/rsyslog.conf
    mode: 0640
    owner: root
    group: root

- name: Setting ownership and permission bits on syslog configuration directory (TBS compliance)
  file:
    path: /etc/rsyslog.d
    mode: 0640
    owner: root
    group: root
    recurse: yes

- name: Setting ownership and permission bits on crontab file (TBS compliance)
  file:
    path: /etc/crontab
    mode: 0600
    owner: root
    group: root

- name: Setting ownership and permission bits on cron.hourly files (TBS compliance)
  file:
    path: /etc/cron.hourly
    mode: 0600
    owner: root
    group: root
    recurse: yes

- name: Setting ownership and permission bits on cron.daily files (TBS compliance)
  file:
    path: /etc/cron.daily
    mode: 0600
    owner: root
    group: root
    recurse: yes

- name: Setting ownership and permission bits on cron.weekly files (TBS compliance)
  file:
    path: /etc/cron.weekly
    mode: 0600
    owner: root
    group: root
    recurse: yes

- name: Setting ownership and permission bits on cron.monthly files (TBS compliance)
  file:
    path: /etc/cron.monthly
    mode: 0600
    owner: root
    group: root
    recurse: yes

- name: Setting ownership and permission bits on cron.d files (TBS compliance)
  file:
    path: /etc/cron.d
    mode: 0600
    owner: root
    group: root
    recurse: yes
