---
- name: Redhat | Adding kernel parameters with value 1 (TBS compliance)
  sysctl:
    name: "{{ item.name }}"
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/10-kernel-hardening.conf
    reload: yes
  with_items:
    - "{{ centos_kernel_params_1 }}"

- name: Redhat | Adding kernel parameters with value 0 (TBS compliance)
  sysctl:
    name: "{{ item.name }}"
    value: 0
    state: present
    sysctl_file: /etc/sysctl.d/10-kernel-hardening.conf
    reload: yes
  with_items:
    - "{{ centos_kernel_params_0 }}"
