---
- name: Installing additional packages on CentOS/RHEL (TBS compliance)
  yum:
    name: "{{ add_el7_packages }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
  
- name: Installing additional packages on CentOS/RHEL (TBS compliance)
  yum:
    name: "{{ add_redhat8_packages }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
  
- name: Installing additional packages on CentOS/RHEL (TBS compliance)
  yum:
    name: "{{ add_el7_packages }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"
  
- name: Installing additional packages on Ubuntu (TBS compliance)
  apt:
    name: "{{ add_deb_packages }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
