---
- name: Configuring NTP on CentOS/RedHat (TBS compliance)
  systemd:
    name: ntpd
    enabled: yes
    state: restarted
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Configuring NTP on Ubuntu (TBS compliance)
  systemd:
    name: ntp
    enabled: yes
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: Adding domain search entry to the DNS resolver file (CentOS/RHEL)
  blockinfile:
    path: /etc/sysconfig/network
    insertafter: EOF
    backup: yes
    state: present
    block: |
      DOMAIN=cloud-dfo-mpo.ca
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Adding domain search entry to the DNS resolver file (Ubuntu)
  blockinfile:
    path: /etc/systemd/resolved.conf
    insertafter: EOF
    backup: yes
    state: present
    block: |
      Domains=cloud-dfo-mpo.ca
  when: ansible_distribution == "Ubuntu"
