---
- hosts: all
  vars:
    MachineDefaults: {}
    SecCat: UN
    TaskCat: AC_3F
  tasks:

  - set_fact:
      Sec_Task: "{{SecCat}}_{{TaskCat}}"

  - name: Initia-friking-lize
    set_fact:
      MachineDefaults: "{{ MachineDefaults
        |combine({ Sec_Task : \"Metroid\" }) }}"

  - debug:
      var: MachineDefaults