# Orchestrator Script
# Fake scripts to test the full structure
---
- hosts: all
  become_method: runas
  vars:
    MachineDefaults: {}
    MachineDefaultsPath: C:\AnsibleMachineDefaults.yml
  tasks:

  - name: Initialize template facts
    set_fact:
      Skips: "{{ Skips|default([]) }}"
      Rollbacks: "{{ Rollbacks|default([]) }}"
      Customs: "{{ Customs|default({}) }}"

  - name: Initialize MachineDefaults dictionary
    include_tasks: WinDefaultsFile.yml
  
  - name: Initialize global Skips
    set_fact:
      Skips: "{{ Skips + [item] }}"
    loop:
      - UN_AC_3F
    when: "'All' in Skips"

  - name: Initialize global Rollbacks
    set_fact:
      Rollbacks: "{{ Rollbacks + [item] }}"
    loop:
      - 'UN_AC_3F'
    when: "'All' in Rollbacks"

  - debug:
      var: Rollbacks


#===== List Script Includes =====#

  - name: Execute UN_AC_3F tasks
    include_tasks: UN_AC_3F.yml
    when: "'UN_AC_3F' not in Skips"