# Orchestrator Script
# Fake scripts to test the full structure
---
- hosts: all
  become_method: runas
  vars:
    MachineDefaults: {}
    MachineDefaultsPath: C:\AnsibleMachineDefaults.yml
  tasks:

  - name: Initialize template facts
    set_fact:
      SkipList: "{{ Skip|default([]) }}"
      UndoList: "{{ Undo|default([]) }}"
      CustomDict: "{{ Custom|default({}) }}"

  - name: Initialize MachineDefaults dictionary
    include_tasks: WinDefaultsFile.yml

  - name: Initialize global SkipList
    set_fact:
      SkipList: "{{ SkipList + [item] }}"
    loop:
      - UN_AC_3F
    when: "'All' in SkipList"

  - debug:
      var: UndoList

  - name: Initialize global UndoList
    set_fact:
      UndoList: "{{ UndoList + [item] }}"
    loop:
      - UN_AC_3F
    when: "'All' in UndoList"

  - debug:
      var: UndoList

  - debug:
      var: SkipList

#===== List Script Includes =====#
  - name: Execute UN_AC_3F tasks
    include_tasks: UN_AC_3F.yml
    when: "'UN_AC_3F' not in SkipList"