# List Script 
# Fake script to test the WinRegedit Task File
---
- hosts: all
  become_method: runas
  vars:
    MachineDefaults: {}
    MachineDefaultsPath: C:\AnsibleMachineDefaults.yml
  tasks:

  - set_fact:
      Skips: "{{ Skips|default(['HeheXD']) }}"

  - set_fact:
      Rollbacks: "{{ Rollbacks|default(['Metroid']) }}"

  - set_fact:
      Customs: "{{ Customs|default({}) }}"

  - debug:
      var: Skips

  - debug:
      var: Rollbacks

  - debug:
      var: Customs

  - name: Initialize MachineDefaults dictionary
    include_tasks: WinDefaultsFile.yml

  - name: Set Regedit tasks dictionary
    set_fact:
      AC_3F_RegTasks:
        - { ID: A, Value: 1, RegType: dword, RegName: LimitBlankPasswordUse, 
        RegPath: 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa', 
        Desc: 'Restrict use of blank passwords'}
        - { ID: B, Value: 1, RegType: dword, RegName: AddPrinterDrivers, 
        RegPath: 'HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers', 
        Desc: 'Prevent printer driver installation for non-admins'}

  - name: Get Regedit Defaults
    include_tasks: WinRegStat.yml
    vars:
      SecCat: UN
      TaskCat: AC_3F
      RegTasks: "{{ AC_3F_RegTasks }}"
    when: "not \"UN_AC_3F\" in MachineDefaults"

  - name: Run Regedit Tasks
    include_tasks: WinRegedit.yml
    vars:
      SecCat: UN
      TaskCat: AC_3F
    loop: "{{ AC_3F_RegTasks }}"
    loop_control:
      loop_var: RegTask