---
# Test playbok for an Windows-Hardening rollback solution

- hosts: all
  become_method: runas
  vars:
    DefRegPath: C:\AnsibleDefaultRegistry.yml
    AC_3: false
    AC_8: false
    SI_3: false
  tasks:

  - name: WinRoll-A > Search for defaults file
    win_stat:
      path: "{{ DefRegPath }}"
    register: PathResult

  - debug:
      var: PathResult

  - name: WinRoll-B > Populate reg key dictionary from file
    slurp: 
      src: "{{ DefRegPath }}"
    register: DefRegFile
    when: PathResult.stat.exists

  - name: WinRoll-C > Decode file contents into reg key dictionary
    set_fact:
      DefReg: "{{ DefRegFile['content'] | b64decode }}" 
    when: PathResult.stat.exists

  - name: WinRoll-D > Collect default reg keys
    win_reg_stat:
      path: "{{ item.path }}"
      name: "{{ item.name }}"
    register: RegVar
    loop:
      - { task: 'AC_3_I', path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon', name: 'ScreenSaverGracePeriod' }
      - { task: 'AC_8_D', path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon', name: 'PasswordExpiryWarning' }
      - { task: 'SI_3_B', path: 'HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds', name: 'DisableEnclosureDownload' }
    when: not PathResult.stat.exists

  - name: WinRoll-E > Populate reg key dictionary from results
    set_fact:
      DefReg: "{{ DefReg|default({}) | combine( {item.item.task: (item.value if item.exists else 'absent')} ) }}"
    loop: "{{ RegVar.results }}"
    when: not PathResult.stat.exists

  - name: WinRoll-F > Write reg key dictionary to file
    win_copy: 
      dest: "{{ DefRegPath }}"
      content: "{{ DefReg }}"
    when: not PathResult.stat.exists

  - debug:
      var: "{{ item }}"
    loop:
      - DefReg
      - DefReg.AC_3_I
      - DefReg.AC_8_D
      - DefReg.SI_3_B

  # Present string key
  - name: AC-3 I > Set screen saver grace period to 4
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: ScreenSaverGracePeriod
      data: 4
      type: string
    when: AC_3

  # Present dword key
  - name: AC-8 D > Set 14-day prompt for user to change password
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: PasswordExpiryWarning
      data: 14
      type: dword
    when: AC_8

  # Non-existent key
  - name: SI-3 B > Prevent downloading of enclosures is set to Enabled
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds
      name: DisableEnclosureDownload
      data: 1
      type: dword
    when: SI_3