---
# Test playbok for an Windows-Hardening rollback solution

- hosts: all
  become_method: runas
  vars:
    RegDefaultsPath: C:\AnsibleDefaultRegistry.yml
  tasks:

  # Retrieve the registry defaults file, or create if non-existent
  - name: WinRoll-A > Search for defaults file
    win_stat:
      path: "{{ RegDefaultsPath }}"
    register: PathResult

  - name: WinRoll-B > Populate reg key dictionary from file
    slurp: 
      src: "{{ RegDefaultsPath }}"
    register: DefaultsFile
    when: PathResult.stat.exists

  - name: WinRoll-C > Decode file contents into reg key dictionary
    set_fact:
      RegistryDefaults: "{{ DefaultsFile['content'] | b64decode }}" 
    when: PathResult.stat.exists

  - name: WinRoll-D > Create defaults file
    win_file:
      path: "{{ RegDefaultsPath }}"
      state: touch
    when: not PathResult.stat.exists

  - name: WinRoll-E > Create RegistryDefaults dictionary
    set_fact:
      RegistryDefaults: { 
        'Registry': 'Defaults' 
      }
    when: not PathResult.stat.exists

  # Supercategory skips for rapid test iteration
  - name: WinRoll-F > Set AC supercategory skip (testing)
    set_fact:
      "skip_UN_AC_{{item}}": true
    loop:
      - 3
      - 4
      - 7
      - 8
      - 11
    when: skip_UN_AC is defined

  - name: WinRoll-G > Set SC supercategory skip (testing)
    set_fact:
      "skip_UN_SC_{{item}}": true
    loop:
      - 2
      - 5
      - 7
      - 8
      - 10
      - 13
      - 23
      - 28
    when: skip_UN_SC is defined

  # Include task categories
  - name: Get Unclassed AC-3 tasks
    include_tasks: UN_AC_3.yml
    when: skip_UN_AC_3 is not defined

  - name: Get Unclassed AC-4 tasks
    include_tasks: UN_AC_4.yml
    when: skip_UN_AC_4 is not defined

  - name: Get Unclassed AC-7 tasks
    include_tasks: UN_AC_7.yml
    when: skip_UN_AC_7 is not defined

  - name: Get Unclassed AC-8 tasks
    include_tasks: UN_AC_8.yml
    when: skip_UN_AC_8 is not defined

  - name: Get Unclassed AC-11 tasks
    include_tasks: UN_AC_11.yml
    when: skip_UN_AC_11 is not defined

  - name: Get Unclassed AU-3 tasks
    include_tasks: UN_AU_3.yml
    when: skip_UN_AU_3 is not defined

  - name: Get Unclassed AU-9 tasks
    include_tasks: UN_AU_9.yml
    when: skip_UN_AU_9 is not defined

  - name: Get Unclassed IA-2 tasks
    include_tasks: UN_IA_2.yml
    when: skip_UN_IA_2 is not defined

  - name: Get Unclassed IA-5 tasks
    include_tasks: UN_IA_5.yml
    when: skip_UN_IA_5 is not defined

  - name: Get Unclassed SC-5 tasks
    include_tasks: UN_SC_5.yml
    when: skip_UN_SC_5 is not defined

# # Task template
# - name: SecCat_TaskCat ID > Description
#   win_regedit:
#     path: RegistryPath
#     name: KeyName
#     data: "{{ SCTMData if undo_SecCat_TaskCat is not defined else RegistryDefaults.SecCat_TaskCat.ID }}"
#     type: DataType
#     state: "{{'absent' if (undo_SecCat_TaskCat is defined and RegistryDefaults.SecCat_TaskCat.ID == 4294967295) else 'present'}}"
#   when: skip_SecCat_TaskCat_ID is not defined