---
# Test playbok for an Windows-Hardening rollback solution

- hosts: all
  become_method: runas
  vars:
    AC_8: false
    SI_3: false
  tasks:

  - name: WinRoll-! > Create reg key file in C
    win_file:
      path: C:\AnsibleDefaultRegistry.JSON
      state: touch
    register: RegFile

  - name: WinRoll-! > Collect default reg keys
    win_reg_stat:
      path: "{{ item.path }}"
      name: "{{ item.name }}"
    register: RegVar
    loop:
      - { task: 'AC-8 D', path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon', name: 'PasswordExpiryWarning' }
      - { task: 'SI-3 B', path: 'HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds', name: 'DisableEnclosureDownload' }

  - name: WinRoll-! > Parse results
    set_fact:
      taskValDict: "{{ 'Exists' if {{ item.exists }} == 'true' else 'Absent' }}"
    loop: "{{ RegVar.results }}"

  - name: WinRoll-! > Debug results
    debug:
      msg: "{{ item.item.task }} - {{ item.item.name }} / exists:{{ item.exists }} changed:{{ item.changed }} failed:{{ item.failed }}"
    loop: "{{ RegVar.results }}"

  - name: WinRoll-! > Debug parsed results
    debug:
      msg: "{{ taskValDict }}"

  # Preset key
  - name: AC-8 D > Set 14-day prompt for user to change password
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: PasswordExpiryWarning
      data: 14
      type: dword
    when: AC_8

  # Non-existent key
  - name: SI-3 B > Prevent downloading of enclosures is set to Enabled
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds
      name: DisableEnclosureDownload
      data: 1
      type: dword
    when: SI_3