---
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'Unclassed' information and data
#
# Author:
#     Alex Imray Papineau
# Last edit:
#     18 April 2019
# Editor:
#     Alex Imray Papineau

- hosts: all
  become_method: runas
  vars:
    RegDefaultsPath: C:\AnsibleDefaultRegistry.yml
  tasks:

  # Retrieve the registry defaults file, or create if non-existent
  - name: Win-UN A > Search for defaults file
    win_stat:
      path: "{{ RegDefaultsPath }}"
    register: PathResult

  - name: Win-UN B > Populate reg key dictionary from file
    slurp: 
      src: "{{ RegDefaultsPath }}"
    register: DefaultsFile
    when: PathResult.stat.exists

  - name: Win-UN C > Decode file contents into reg key dictionary
    set_fact:
      RegistryDefaults: "{{ DefaultsFile['content'] | b64decode }}" 
    when: PathResult.stat.exists

  - name: Win-UN D > Create defaults file
    win_file:
      path: "{{ RegDefaultsPath }}"
      state: touch
    when: not PathResult.stat.exists

  - name: Win-UN E > Create RegistryDefaults dictionary
    set_fact:
      RegistryDefaults: { 
        'Registry': 'Defaults' 
      }
    when: not PathResult.stat.exists

  # Supercategory skips for rapid test iteration
  - name: Win-UN F > Set AC supercategory skip (testing)
    set_fact:
      "skip_UN_AC_{{item}}": true
    loop:
      - 3
      - 4
      - 7
      - 8
      - 11
    when: skip_UN_AC is defined

  - name: Win-UN G > Set AU supercategory skip (testing)
    set_fact:
      "skip_UN_AU_{{item}}": true
    loop:
      - 3
      - 9
    when: skip_UN_AU is defined

  - name: Win-UN H > Set IA supercategory skip (testing)
    set_fact:
      "skip_UN_IA_{{item}}": true
    loop:
      - 2
      - 5
    when: skip_UN_IA is defined

  - name: Win-UN I > Set SC supercategory skip (testing)
    set_fact:
      "skip_UN_SC_{{item}}": true
    loop:
      - '2_7_10'
      - 5
      - 8
    when: skip_UN_SC is defined

  - name: Win-UN J > Set SI supercategory skip (testing)
    set_fact:
      "skip_UN_SI_{{item}}": true
    loop:
      - 2
      - 3
    when: skip_UN_SI is defined

  # Supercategory rollbacks (undo)
  - name: Win-UN K > Set global undo
    set_fact:
      "undo_UN_{{item}}": true
    loop:
      - AC
      - AU
      - IA
      - SC
      - SI
    when: undo_UN_All is defined
  
  - name: Win-UN L > Set AC supercategory undo
    set_fact:
      "undo_UN_AC_{{item}}": true
    loop:
      - 3
      - 4
      - 7
      - 8
      - 11
    when: undo_UN_AC is defined

  - name: Win-UN M > Set AU supercategory undo
    set_fact:
      "undo_UN_AU_{{item}}": true
    loop:
      - 3
      - 9
    when: undo_UN_AU is defined

  - name: Win-UN N > Set IA supercategory undo
    set_fact:
      "undo_UN_IA_{{item}}": true
    loop:
      - 2
      - 5
    when: undo_UN_IA is defined

  - name: Win-UN O > Set SC supercategory undo
    set_fact:
      "undo_UN_SC_{{item}}": true
    loop:
      - 2
      - 5
      - 7
      - 8
      - 10
    when: undo_UN_SC is defined

  - name: Win-UN P > Set SI supercategory undo
    set_fact:
      "undo_UN_SI_{{item}}": true
    loop:
      - 2
      - 3
    when: undo_UN_SI is defined

  # Include task categories
  - name: Get Unclassed AC-3 tasks (A-UU)
    include_tasks: UN_AC_3.yml
    when: skip_UN_AC_3 is not defined

  - name: Get Unclassed AC-4 tasks (A-D)
    include_tasks: UN_AC_4.yml
    when: skip_UN_AC_4 is not defined

  - name: Get Unclassed AC-7 tasks (A-C)
    include_tasks: UN_AC_7.yml
    when: skip_UN_AC_7 is not defined

  - name: Get Unclassed AC-8 tasks (A-E)
    include_tasks: UN_AC_8.yml
    when: skip_UN_AC_8 is not defined

  - name: Get Unclassed AC-11 tasks (A-D)
    include_tasks: UN_AC_11.yml
    when: skip_UN_AC_11 is not defined

  - name: Get Unclassed AU-3 tasks (A-C)
    include_tasks: UN_AU_3.yml
    when: skip_UN_AU_3 is not defined

  - name: Get Unclassed AU-9 tasks (A-C)
    include_tasks: UN_AU_9.yml
    when: skip_UN_AU_9 is not defined

  - name: Get Unclassed IA-2 tasks (A-C)
    include_tasks: UN_IA_2.yml
    when: skip_UN_IA_2 is not defined

  - name: Get Unclassed IA-5 tasks (A-L)
    include_tasks: UN_IA_5.yml
    when: skip_UN_IA_5 is not defined

  - name: Get Unclassed SC-2, SC-7, and SC-10 tasks (3)
    include_tasks: UN_SC_2_7_10.yml
    when: skip_UN_SC_2_7_10 is not defined

  - name: Get Unclassed SC-5 tasks (A-E)
    include_tasks: UN_SC_5.yml
    when: skip_UN_SC_5 is not defined

  - name: Get Unclassed SC-8 tasks (A-Q)
    include_tasks: UN_SC_8.yml
    when: skip_UN_SC_8 is not defined

  - name: Get Unclassed SI-2 tasks (A-B)
    include_tasks: UN_SI_2.yml
    when: skip_UN_SI_2 is not defined

  - name: Get Unclassed SI-3 tasks (A-E)
    include_tasks: UN_SI_3.yml
    when: skip_UN_SI_3 is not defined

  - name: Get former Secedit tasks (U-NN)
    include_tasks: UN_Secedit.yml
    when: skip_UN_Secedit is not defined

# # Task template
# - name: SecCat_TaskCat ID > Description
#   win_regedit:
#     path: RegistryPath
#     name: KeyName
#     data: "{{ SCTMData if undo_SecCat_TaskCat is not defined else RegistryDefaults.SecCat_TaskCat.ID }}"
#     type: DataType
#     state: "{{'absent' if (undo_SecCat_TaskCat is defined and RegistryDefaults.SecCat_TaskCat.ID == 4294967295) else 'present'}}"
#   when: skip_SecCat_TaskCat_ID is not defined