---
# Test playbok for an Windows-Hardening rollback solution

- hosts: all
  become_method: runas
  vars:
    DefRegPath: C:\AnsibleDefaultRegistry.yml
    AC_8: false
    SI_3: false
  tasks:

  - name: WinRoll-! > Create reg key file in C
    win_file:
      path: "{{ DegRefPath }}"
      state: touch

  - name: WinRoll-! > Collect default reg keys
    win_reg_stat:
      path: "{{ item.path }}"
      name: "{{ item.name }}"
    register: RegVar
    loop:
      - { task: 'AC_8_D', path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon', name: 'PasswordExpiryWarning' }
      - { task: 'SI_3_B', path: 'HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds', name: 'DisableEnclosureDownload' }

  - name: WinRoll-! > Populate reg key dictionary
    set_fact:
      DefReg: "{{ DefReg|default({}) | combine( {item.item.task: (item.value if item.exists else 'absent')} ) }}"
    loop: "{{ RegVar.results }}"

  - debug:
      var: DefReg

  - name: Write reg key dictionary to file
    win_copy: 
      dest: "{{ DefRegPath }}"
      content: "{{ DefReg }}"

  # Preset key
  - name: AC-8 D > Set 14-day prompt for user to change password
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: PasswordExpiryWarning
      data: 14
      type: dword
    when: AC_8

  # Non-existent key
  - name: SI-3 B > Prevent downloading of enclosures is set to Enabled
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds
      name: DisableEnclosureDownload
      data: 1
      type: dword
    when: SI_3