---
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'unclassed' information
#
# Author:
#     Alex Imray Papineau
# Last edit:
#     26 Match 2019
# Editor:
#     Alex Imray Papineau

- name: Get Security Policy Tasks
  import_playbook: security_policy.yml

- hosts: all
  become_method: runas
  vars:
    AC_3: true
    AC_4: true
    AC_7: true
    AC_8: true
    AC_11: true

    AU_3: true
    AU_9: true

    CM_3: false
    CM_6: false
    
    IA_2: false
    IA_5: true
    
    SC_2: false
    SC_8: false
    SC_5: false
    SC_7: false
    SC_13: false
    SC_10: false
    SC_15: false
    SC_23: false
    SC_28: false

    SI_2: false
    SI_3: false

  tasks:

  - name: Get AC-3 Compliance Tasks A-Z
    include_tasks: AC-3_Tasks.yml
    when: AC_3

  - name: Get AC-8 Compliance Tasks A-E
    include_tasks: AC-8_Tasks.yml
    when: AC_8

  - name: Get IA-5 Compliance Tasks A-L
    include_tasks: IA-5_Tasks.yml
    when: IA_5

  - name: Get SC-5 Compliance Tasks A-E
    include_tasks: SC-5_Tasks.yml
    when: SC_5 or SI_2 or SC_23

  - name: Get SC-8 Compliance Tasks A-I
    include_tasks: SC-8_Tasks.yml
    when: CM_3 or SC_2 or SC_8 or SC_23 or SC_28

  - name: Get SI-3 Compliance Tasks A-E
    include_tasks: SI-3_Tasks.yml
    when: SI_3

# AC-4
  - name: AC-4 A > Prevent storing LAN Manager hash value
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: NoLmHash
      data: 1
      type: dword
    when: AC_4

  - name: AC-4 B > Set LAN Manager authentication
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: lmcompatibilitylevel
      data: 5
      type: dword
    when: AC_4

  - name: AC-4 C > Set minimum server network traffic security
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
      name: NtkmMinServerSec
      data: 20000000
      type: dword
    when: AC_4 or CM_3

  - name: AC-4 > Prohibit connection between secure and insecure networks
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy
      name: fBlockNonDomain
      data: 1
      type: dword
    when: AC_4

# AC-7
  - name: AC-7 A > 
    win_command: "net accounts /lockoutthreshold:5"
    when: AC_7

  - name: AC-7 B > 
    win_command: "net accounts /lockoutduration:60"
    when: AC_7

  - name: AC-7 C > 
    win_command: "net accounts /lockoutwindow:60"
    when: AC_7

# AC-11
  - name: AC-11 A > Password-protect screen saver
    win_regedit:
      path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverIsSecure
      data: 1
      type: string
    when: AC_11

  - name: AC-11 B > Screen saver activates after 5 mins of inactivity
    win_regedit:
      path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverTimeOut
      data: 600
      type: string
    when: AC_11

  - name: AC-11 C (DC)
    block:
      - name: AC-11 > Require password when waking computer (DC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: DCSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'DCSettingIndex' is not present for this computer"
    when: AC_11

  - name: AC-11 D (AC)
    block:
      - name: AC-11 > Require password when waking computer (AC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: ACSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'ACSettingIndex' is not present for this computer"
    when: AC_11

# AU-3
  - name: AU-3 > Ensure firewalls log dropped packets
    win_regedit:
      path: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item }}\\Logging"
      name: LogDroppedPackets
      data: 1
      type: dword
    loop:
      - DomainProfile
      - PrivateProfile
      - PublicProfile
    when: AU_3

# AU-9
  - name: AU-9 > Ensure firewalls log to correct files
    win_regedit:
      path: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item.path }}\\Logging"
      name: LogFilePath
      data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\{{ item.file }}"
      type: string
    loop:
      - { path: DomainProfile, file: domainfw.log }
      - { path: PrivateProfile, file: privatefw.log }
      - { path: PublicProfile, file: publicfw.log }
    when: AU_9

# IA-2
  - name: IA-2 A > Prevent NULL session fallback
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
      name: allownullsessionfallback
      data: 0
      type: dword
    when: IA_2

  - name: IA-2 B > Prevent online identity use for PKU2U authentication requests
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u
      name: allowonlineid # OwO
      data: 0
      type: dword
    when: IA_2

  - name: IA-2 C > Enforce password prompt for RDP
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
      name: fPromptForPassword
      data: 1
      type: dword
    when: IA_2

# SC-2
  - name: SC-2 > Prohibit IP source routing
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
      name: DisableIPSourceRouting
      data: 2
      type: dword
    when: SC_2

# SC-7
  - name: SC-7 > Prevent bypassing SmartScreen prompts
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: PreventOverride
      data: 1
      type: dword
    when: SC_7

# SC-10
  - name: SC-10 > Limit idle RDP sessions to 15 mins
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
      name: MaxIdleTime
      data: 900000
      type: dword
    when: SC_10

# SI-3
  - name: SI-3 A > Prevent attachment downloads through RSS
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds
      name: DisableEnclosureDownload
      data: 1
      type: dword
    when: SI_3

  - name: SI-3 B >
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments
      name: ScanWithAntiVirus
      data: 3
      type: dword
    when: SI_3
