---
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'unclassed' information
#
# Author:
#     Alex Imray Papineau
# Last edit:
#     26 Match 2019
# Editor:
#     Alex Imray Papineau

## Task template
  # - name: 
  #   win_regedit:
  #     path: 
  #     name: 
  #     data: 
  #     type: 
  #   when: 

- hosts: all
  become_method: runas
  vars:
    SC_8: true
    SC_5: true
    SC_23: true
    AC_11: true
    SC_7: true
    SC_10: true

  tasks:
  
  - name: SC-8 A > Comply with CSE ITSP.40.062 (Ciphers)
    win_regedit:
      path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\{{ item }}"
      name: Enabled
      data: 0
      type: dword
    loop:
      - 'RC4 128/128'
      - 'RC2 128/128'
      - 'RC4 64/128'
      - 'RC4 56/128'
      - 'RC2 56/128'
      - 'RC4 40/128'
      - 'RC2 40/128'
      - 'NULL'
    when: SC_8

  - name: SC-8 B > Comply with CSE ITSP.40.062 (Hashes)
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\MD5
      name: Enabled
      data: 0
      type: dword
    when: SC_8

  - name: SC-5 A > Limit unacknowledged data retransmission (IPv6)
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\TCPIP6\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
    when: SC_5

  - name: SC-5 B > Limit unacknowledged data retransmission
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
    when: SC_5

  - name: SC-5 C > Set keep-alive packet send interval
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: KeepAliveTime
      data: 300000
      type: dword
    when: SC_5

  - name: SC-5 D & SC-23 > Disable IRDP Default Gateway configuration
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: PerformRouterDiscovery
      data: 0
      type: dword
    when: SC_5 or SC_23

  - name: AC-11 (DC)
    block:
      - name: AC-11 > Require password when waking computer (DC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: DCSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'DCSettingIndex' is not present for this computer"
    when: AC_11

  - name: AC-11 (AC)
    block:
      - name: AC-11 > Require password when waking computer (AC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: ACSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'ACSettingIndex' is not present for this computer"
    when: AC_11

  - name: SC-7 > Prevent bypassing SmartScreen prompts
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: PreventOverride
      data: 1
      type: dword
    when: SC_7

  - name: SC-10 > Limit idle RDP sessions to 15 mins
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
      name: MaxIdleTime
      data: 900000
      type: dword
    when: SC_10