---
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'unclassed' information
#
# Author:
#     Alex Imray Papineau
# Last edit:
#     26 Match 2019
# Editor:
#     Alex Imray Papineau

## Task template
  # - name: 
  #   win_regedit:
  #     path: 
  #     name: 
  #     data: 
  #     type: 
  #   when: 

- hosts: all
  become_method: runas
  vars:
    CM_3: true
    SI_2: true
    SI_3: true
    IA_5: true
    AC_3: false
    AC_4: false
    AU_9: false
    AU_3: false
    SC_8: true
    SC_5: false
    SC_23: false
    AC_11: false
    SC_7: false
    SC_10: false

  tasks:

  - name: SI-2 & SC-5 > Set computer to restart for updates even if user(s) logged in
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: NoAutoRebootWithLoggedOnUsers
      data: 0
      type: dword
    when: SI_2 or SC_5

  - name: SI-3 > Ensure antivirus programs check attachments
    win_regedit:
      path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
      name: ScanWithAntiVirus
      data: 3
      type: dword
    when: SI_3

  - name: Get IA-5 Compliance Tasks
    include_tasks: IA-5_tasks.yml
    when: IA_5

  - name: AC-3 A > Require authentication for RPC service access
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Rpc
      name: EnableAuthEpResolution
      data: 1
      type: dword
    when: AC_3

  - name: AC-3 B > Require Domain Controller Authentication to unlock computer
    win_regedit:
      path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: ForceUnlockLogon
      data: 1
      type: dword
    when: AC_3

  - name: AC-4 > Prohibit connection between secure and insecure networks
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy
      name: fBlockNonDomain
      data: 1
      type: dword
    when: AC_4

  - name: AU-9 > Ensure firewalls log to correct files
    win_regedit:
      path: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item.path }}\\Logging"
      name: LogFilePath
      data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\{{ item.file }}"
      type: string
    loop:
      - { path: DomainProfile, file: domainfw.log }
      - { path: PrivateProfile, file: privatefw.log }
      - { path: PublicProfile, file: publicfw.log }
    when: AU_9

  - name: AU-3 > Ensure firewalls log dropped packets
    win_regedit:
      path: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item }}\\Logging"
      name: LogDroppedPackets
      data: 1
      type: dword
    loop:
      - DomainProfile
      - PrivateProfile
      - PublicProfile
    when: AU_3

  - name: SC-8 D > Prevent unencrypted client traffic
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client
      name: AllowUnencryptedTraffic
      data: 0
      type: dword
    when: SC_8

  - name: SC-8 E > Prevent unencrypted service traffic
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service
      name: AllowUnencryptedTraffic
      data: 0
      type: dword
    when: SC_8
  
  - name: SC-8 F > Comply with CSE ITSP.40.062 (Ciphers)
    win_regedit:
      path: "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\{{ item }}"
      name: Enabled
      data: 0
      type: dword
    loop:
      - 'RC4 128/128'
      - 'RC2 128/128'
      - 'RC4 64/128'
      - 'RC4 56/128'
      - 'RC2 56/128'
      - 'RC4 40/128'
      - 'RC2 40/128'
      - 'NULL'
    when: SC_8

  - name: SC-8 G > Comply with CSE ITSP.40.062 (Hashes)
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\MD5
      name: Enabled
      data: 0
      type: dword
    when: SC_8

  - name: SC-5 A > Limit unacknowledged data retransmission (IPv6)
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\TCPIP6\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
    when: SC_5

  - name: SC-5 B > Limit unacknowledged data retransmission
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
    when: SC_5

  - name: SC-5 C > Set keep-alive packet send interval
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: KeepAliveTime
      data: 300000
      type: dword
    when: SC_5

  - name: SC-5 D & SC-23 > Disable IRDP Default Gateway configuration
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: PerformRouterDiscovery
      data: 0
      type: dword
    when: SC_5 or SC_23

  - name: AC-11 A > Password-protect screen saver
    win_regedit:
      path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverIsSecure
      data: 1
      type: string
    when: AC_11

  - name: AC-11 B > Screen saver activates after 5 mins of inactivity
    win_regedit:
      path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverTimeOut
      data: 600
      type: string
    when: AC_11

  - name: AC-11 C (DC)
    block:
      - name: AC-11 > Require password when waking computer (DC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: DCSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'DCSettingIndex' is not present for this computer"
    when: AC_11

  - name: AC-11 D (AC)
    block:
      - name: AC-11 > Require password when waking computer (AC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: ACSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'ACSettingIndex' is not present for this computer"
    when: AC_11

  - name: SC-7 > Prevent bypassing SmartScreen prompts
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: PreventOverride
      data: 1
      type: dword
    when: SC_7

  - name: SC-10 > Limit idle RDP sessions to 15 mins
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
      name: MaxIdleTime
      data: 900000
      type: dword
    when: SC_10