---
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'unclassed' information
#
# Author:
#     Alex Imray Papineau
# Last edit:
#     26 Match 2019
# Editor:
#     Alex Imray Papineau

- hosts: all
  become_method: runas
  vars:
    AC_11: true
    SC_7: true
    SC_10: true

  tasks:


  # If either DCSettingIndex or ACSettingIndex is available on all computers, the two AC-11 tasks can be combined
  - name: AC-11 (DC)
    block:
      - name: AC-11 > Require password when waking computer (DC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: DCSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'DCSettingIndex' is not present for this computer"
    when: AC_11

  - name: AC-11 (AC)
    block:
      - name: AC-11 > Require password when waking computer (AC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: ACSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'ACSettingIndex' is not present for this computer"
    when: AC_11

  - name: SC-7 > Prevent bypassing SmartScreen prompts
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: PreventOverride
      data: 1
      type: dword
    when: SC_7

  - name: SC-10 > Limit idle RDP sessions to 15 mins
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
      name: MaxIdleTime
      data: 60000
      type: dword
    when: SC_10
