---
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'unclassed' information
#
# Author:
#     Alex Imray Papineau
# Last edit:
#     26 Match 2019
# Editor:
#     Alex Imray Papineau

## Task template
  # - name: 
  #   win_regedit:
  #     path: 
  #     name: 
  #     data: 
  #     type: 
  #   when: 

- hosts: all
  become_method: runas
  vars:
    AC_3: false
    AC_4: false
    AC_7: true
    AC_11: false

    AU_3: false
    AU_9: false

    CM_3: true
    CM_6: true
    
    IA_5: true
    
    SC_2: true
    SC_8: true
    SC_5: false
    SC_7: false
    SC_13: false
    SC_10: false
    SC_15: true
    SC_23: false
    SC_28: false

    SI_2: true
    SI_3: true

  tasks:

  - name: Get AC-3 Compliance Tasks
    include_tasks: AC-3_Tasks.yml
    when: AC_3

  - name: Get Security Policy Tasks
    import_playbook: security_policy.yml
    when: AC_3 or AC_7 or AU_9 or CM_6 or SC_5 or SC_15

  - name: Get IA-5 Compliance Tasks
    include_tasks: IA-5_Tasks.yml
    when: IA_5

  - name: Get SC-8 Compliance Tasks
    include_tasks: SC-8_Tasks.yml
    when: CM_3 or SC_2 or SC_8 or SC_23 or SC_28

  - name: Get SI-3 Compliance Tasks
    include_tasks: SI-3_Tasks.yml
    when: SI_3

  - name: SI-2 & SC-5 > Set computer to restart for updates even if user(s) logged in
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: NoAutoRebootWithLoggedOnUsers
      data: 0
      type: dword
    when: SI_2 or SC_5

  - name: AC-4 > Prohibit connection between secure and insecure networks
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy
      name: fBlockNonDomain
      data: 1
      type: dword
    when: AC_4

  - name: AU-9 > Ensure firewalls log to correct files
    win_regedit:
      path: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item.path }}\\Logging"
      name: LogFilePath
      data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\{{ item.file }}"
      type: string
    loop:
      - { path: DomainProfile, file: domainfw.log }
      - { path: PrivateProfile, file: privatefw.log }
      - { path: PublicProfile, file: publicfw.log }
    when: AU_9

  - name: AU-3 > Ensure firewalls log dropped packets
    win_regedit:
      path: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item }}\\Logging"
      name: LogDroppedPackets
      data: 1
      type: dword
    loop:
      - DomainProfile
      - PrivateProfile
      - PublicProfile
    when: AU_3

  - name: SC-5 A > Limit unacknowledged data retransmission (IPv6)
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\TCPIP6\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
    when: SC_5

  - name: SC-5 B > Limit unacknowledged data retransmission
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
    when: SC_5

  - name: SC-5 C > Set keep-alive packet send interval
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: KeepAliveTime
      data: 300000
      type: dword
    when: SC_5

  - name: SC-5 D & SC-23 > Disable IRDP Default Gateway configuration
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: PerformRouterDiscovery
      data: 0
      type: dword
    when: SC_5 or SC_23

  - name: AC-11 A > Password-protect screen saver
    win_regedit:
      path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverIsSecure
      data: 1
      type: string
    when: AC_11

  - name: AC-11 B > Screen saver activates after 5 mins of inactivity
    win_regedit:
      path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverTimeOut
      data: 600
      type: string
    when: AC_11

  - name: AC-11 C (DC)
    block:
      - name: AC-11 > Require password when waking computer (DC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: DCSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'DCSettingIndex' is not present for this computer"
    when: AC_11

  - name: AC-11 D (AC)
    block:
      - name: AC-11 > Require password when waking computer (AC)
        win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
          name: ACSettingIndex
          data: 1
          type: dword
    rescue:
      - debug:
          msg: "Registry Entry 'ACSettingIndex' is not present for this computer"
    when: AC_11

  - name: SC-7 > Prevent bypassing SmartScreen prompts
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: PreventOverride
      data: 1
      type: dword
    when: SC_7

  - name: SC-10 > Limit idle RDP sessions to 15 mins
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
      name: MaxIdleTime
      data: 900000
      type: dword
    when: SC_10