# == Orchestrator Script ==
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'Protected B-Medium-Medium' information
---
- hosts: windows
  become_method: runas
  vars:
    MachineDefaults: {}
    MachineDefaultsPath: C:\AnsibleMachineDefaults.yml
  tasks:

  - name: Initialize template facts
    set_fact:
      SkipList: "{{ Skip|default([]) }}"
      UndoList: "{{ Undo|default([]) }}"
      CustomDict: "{{ Custom|default({}) }}"
      OnlyRun: "{{ OnlyRun|default('None') }}"

  - name: Initialize MachineDefaults dictionary
    include_tasks: TaskScripts/WinDefaultsFile.yml
    when: not 'All' in SkipList

  - name: Initialize SkipList array
    include_tasks: TaskScripts/InitSkips.yml

  - name: Initialize UndoList array
    include_tasks: TaskScripts/InitUndos.yml

#========== List Script Includes ==========#
  # AC
  - name: Execute ULL_AC_3 tasks
    include_tasks: WinUnclassed/ULL_AC_3.yml
    when: "'ULL_AC_3' not in SkipList"

  - name: Execute ULL_AC_4 tasks
    include_tasks: WinUnclassed/ULL_AC_4.yml
    when: "'ULL_AC_4' not in SkipList"

  - name: Execute ULL_AC_7 tasks
    include_tasks: WinUnclassed/ULL_AC_7.yml
    when: "'ULL_AC_7' not in SkipList"

  - name: Execute ULL_AC_8 tasks
    include_tasks: WinUnclassed/ULL_AC_8.yml
    when: "'ULL_AC_8' not in SkipList"

  - name: Execute ULL_AC_11 tasks
    include_tasks: WinUnclassed/ULL_AC_11.yml
    when: "'ULL_AC_11' not in SkipList"

  # AU
  - name: Execute ULL_AU_3 tasks
    include_tasks: WinUnclassed/ULL_AU_3.yml
    when: "'ULL_AU_3' not in SkipList"

  - name: Execute ULL_AU_9 tasks
    include_tasks: WinUnclassed/ULL_AU_9.yml
    when: "'ULL_AU_9' not in SkipList"

  # IA
  - name: Execute ULL_IA_2 tasks
    include_tasks: WinUnclassed/ULL_IA_2.yml
    when: "'ULL_IA_2' not in SkipList"

  - name: Execute ULL_IA_5 tasks
    include_tasks: WinUnclassed/ULL_IA_5.yml
    when: "'ULL_IA_5' not in SkipList"

  # SC
  - name: Execute ULL_SC_2_7_10 tasks
    include_tasks: WinUnclassed/ULL_SC_2_7_10.yml
    when: "'ULL_SC' not in SkipList"

  - name: Execute ULL_SC_5 tasks
    include_tasks: WinUnclassed/ULL_SC_5.yml
    when: "'ULL_SC_5' not in SkipList"

  - name: Execute ULL_SC_8 tasks
    include_tasks: WinUnclassed/ULL_SC_8.yml
    when: "'ULL_SC_8' not in SkipList"

  # SI
  - name: Execute ULL_SI_2 tasks
    include_tasks: WinUnclassed/ULL_SI_2.yml
    when: "'ULL_SI_2' not in SkipList"

  - name: Execute ULL_SI_3 tasks
    include_tasks: WinUnclassed/ULL_SI_3.yml
    when: "'ULL_SI_3' not in SkipList"

# PBMM
  - name: Execute PBMM AC tasks
    include_tasks: WinPBMM/PBMM_AC.yml

  - name: Execute PBMM AU tasks
    include_tasks: WinPBMM/PBMM_AU.yml

  - name: Execute PBMM IA tasks
    include_tasks: WinPBMM/PBMM_IA.yml

# PBMM BGInfo
  - name: Execute PBMM BGInfo tasks
    include_tasks: WinPBMM/PBMM_BGInfo.yml