# == Orchestrator Script ==
# STCM-DFO-IaaS compliant configuration for
# a Windows virtual machine in Azure Cloud
# Based on RFP 16-42051B
#
# A Windows VM in Azure Cloud with this
# configuration may contain Government of
# Canada 'Unclassed' information
---
- hosts: all
  become_method: runas
  vars:
    MachineDefaults: {}
    MachineDefaultsPath: C:\AnsibleMachineDefaults.yml
  tasks:

  - name: Initialize template facts
    set_fact:
      SkipList: "{{ Skip|default([]) }}"
      UndoList: "{{ Undo|default([]) }}"
      CustomDict: "{{ Custom|default({}) }}"
      OnlyRun: "{{ OnlyRun|default('None') }}"

  - name: Initialize MachineDefaults dictionary
    include_tasks: WinDefaultsFile.yml

  - name: Initialize SkipList array
    include_tasks: InitSkips.yml

  - name: Initialize UndoList array
    include_tasks: InitUndos.yml

#========== List Script Includes ==========#
  # AC
  - name: Execute UN_AC_3 tasks
    include_tasks: UN_AC_3.yml
    when: "'UN_AC_3' not in SkipList"

  - name: Execute UN_AC_4 tasks
    include_tasks: UN_AC_4.yml
    when: "'UN_AC_4' not in SkipList"

  - name: Execute UN_AC_7 tasks
    include_tasks: UN_AC_7.yml
    when: "'UN_AC_7' not in SkipList"

  - name: Execute UN_AC_8 tasks
    include_tasks: UN_AC_8.yml
    when: "'UN_AC_8' not in SkipList"

  - name: Execute UN_AC_11 tasks
    include_tasks: UN_AC_11.yml
    when: "'UN_AC_11' not in SkipList"

  # AU
  - name: Execute UN_AU_3 tasks
    include_tasks: UN_AU_3.yml
    when: "'UN_AU_3' not in SkipList"

  - name: Execute UN_AU_9 tasks
    include_tasks: UN_AU_9.yml
    when: "'UN_AU_9' not in SkipList"

  # IA
  - name: Execute UN_IA_2 tasks
    include_tasks: UN_IA_2.yml
    when: "'UN_IA_2' not in SkipList"

  - name: Execute UN_IA_5 tasks
    include_tasks: UN_IA_5.yml
    when: "'UN_IA_5' not in SkipList"

  # SC
  - name: Execute UN_SC_2_7_10 tasks
    include_tasks: UN_SC_2_7_10.yml
    when: "'UN_SC' not in SkipList"

  - name: Execute UN_SC_5 tasks
    include_tasks: UN_SC_5.yml
    when: "'UN_SC_5' not in SkipList"

  - name: Execute UN_SC_8 tasks
    include_tasks: UN_SC_8.yml
    when: "'UN_SC_8' not in SkipList"

  # SI
  - name: Execute UN_SI_2 tasks
    include_tasks: UN_SI_2.yml
    when: "'UN_SI_2' not in SkipList"

  - name: Execute UN_SI_3 tasks
    include_tasks: UN_SI_3.yml
    when: "'UN_SI_3' not in SkipList"