---
- name: Configuring NTP on CentOS/RedHat (TBS compliance)
  systemd:
    name: ntpd
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Configuring NTP on Ubuntu (TBS compliance)
  systemd:
    name: ntp
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"
