---
- name: Configuring NTP on CentOS/RedHat (TBS compliance)
  systemd:
    name: ntpd
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS"

- name: Configuring NTP on CentOS/RedHat (TBS compliance)
  systemd:
    name: ntpd
    enabled: yes
    state: started
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- name: Configuring NTP on Ubuntu (TBS compliance)
  systemd:
    name: ntp
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"
