---
- name: Adding FileCreateMode on /var/log directory (TBS compliance)
  blockinfile:
    path: /etc/rsyslog.conf
    insertafter: EOF
    state: present
    block: |
      $FileCreateMode 640
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

#- name: Find log directories
#  find:
#    paths: /var/log
#    file_type: directory
#    recurse: yes
#  register: logdirs

#- name: Set permissions on log directories.
#  file:
#    path: "{{ item.path }}"
#    mode: 0755
#  with_items: "{{ logdirs.files }}"

#- name: Find log files
#  find:
#    paths: /var/log
#    file_type: file
#    recurse: yes
#  register: logfiles

#- name: Removing excessive permission bits from log files (TBS compliance)
#  file:
#    path: "{{ item.path }}"
#    mode: 0640
#  with_items: "{{ logfiles.files }}"

- name: Ensure log directories are 0755
  command: find /var/log -type d -exec chmod 0755 {} \;
  changed_when: false
  
- name: Ensure files are 0640
  command: find /var/log -type f -exec chmod 0640 {} \;
  changed_when: false

- name: Setting ownership and permission bits on syslog configuration file (TBS compliance)
  file:
    path: /etc/rsyslog.conf
    mode: 0640
    owner: root
    group: root

- name: Setting ownership and permission bits on syslog configuration directory (TBS compliance)
  file:
    path: /etc/rsyslog.d
    mode: 0740
    owner: root
    group: root
    recurse: yes
