---
- name: Adding minimum user password validity setting (TBS compliance)
  lineinfile:
    path: /etc/login.defs
    regex: "PASS_MIN_DAYS"
    line: "PASS_MIN_DAYS 7"
    state: present

- name: Adding maximum user password validity setting (TBS compliance)
  lineinfile:
    path: /etc/login.defs
    regex: "PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS 90"
    state: present

- name: Adding warning days (TBS compliance)
  lineinfile:
    path: /etc/login.defs
    regex: "PASS_WARN_AGE"
    line: "PASS_WARN_AGE 14"
    state: present

- name: Setting the default password inactivity period for new users to 30 days (TBS compliance)
  lineinfile:
    path: /etc/default/useradd
    regex: "INACTIVE"
    line: "INACTIVE=30"
    state: present
